services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis/redis-stack:latest
    ports:
      - "8001:8001"
      - "6379:6379"
    environment:
        REDIS_ARGS: --requirepass password
    volumes:
      - ./data/redis:/data
  web:
    extends:
      file: base.docker-compose.yml
      service: discourse
    # command: bash -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0 -p 3000"
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./data/web-log:/var/www/discourse/log/
  sidekiq:
    extends:
      file: base.docker-compose.yml
      service: discourse
    # COpied from demon/sidekiq.rb
    command: bundle exec sidekiq -q critical,8 -q default,4 -q low,2 -q ultra_low,1 --verbose
    depends_on:
      - db
      - redis
    volumes:
      - ./data/sidekiq-log:/var/www/discourse/log/
