services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: redis
  web:
    image: discourse
    build: .
    environment:
      # Need to pretend its not localhost or else will error
      - DISCOURSE_HOSTNAME=forum.valleyhousing.coop:3000
      - DISCOURSE_DB_HOST=db
      - DISCOURSE_DB_PORT=5432
      - DISCOURSE_DB_NAME=postgres
      - DISCOURSE_DB_USERNAME=postgres
      - DISCOURSE_DB_PASSWORD=password
      - DISCOURSE_REDIS_HOST=redis
      - RAILS_ENV=production
      - DISCOURSE_SERVE_STATIC_ASSETS=true
    # command: bash -c "bundle exec rake assets:precompile && bundle exec rails server -b 0.0.0.0 -p 3000"
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - ./assets:/var/www/discourse/public/assets/
      - ./log:/var/www/discourse/log/
