services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  redis:
    image: redis
  # minio:
  #   image: minio/minio
  #   ports:
  #     - "9000:9000"
  #     - "9001:9001"
  #   volumes:
  #     - ./minio:/data
  #   environment:
  #     MINIO_ROOT_USER: user
  #     MINIO_ROOT_PASSWORD: password
  #   command: server --console-address ":9001" /data
  web:
    image: discourse
    build: .
    environment:
      - DISCOURSE_HOSTNAME=forum.valleyhousing.coop
      - DISCOURSE_DB_HOST=db
      - DISCOURSE_DB_PORT=5432
      - DISCOURSE_DB_NAME=postgres
      - DISCOURSE_DB_USERNAME=postgres
      - DISCOURSE_DB_PASSWORD=password
      - DISCOURSE_REDIS_HOST=redis
      - RAILS_ENV=production
      # - APP_ROOT=/var/www/discourse
      # https://github.com/minio/minio/issues/4769
      # - DISCOURSE_USE_S3=true
      # - DISCOURSE_S3_REGIOM=anything
      # - DISCOURSE_S3_ENDPOINT=minio:9000
      # - DISCOURSE_S3_ACCESS_KEY_I=user
      # - DISCOURSE_S3_SECRET_ACCESS_KEY=password
      # - DISCOURSE_S3_CDN_UR=http://discourse-data-cdn.example.com
      # - DISCOURSE_S3_BUCKET=discourse-data
      # - DISCOURSE_S3_BACKUP_BUCKET=discourse-backups
      # - DISCOURSE_BACKUP_LOCATION=s3
      # - DISCOURSE_S3_INSTALL_CORS_RULE=false
    command: bundle exec rails server -b 0.0.0.0 -p 3000 --log-to-stdout
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      # - minio
    volumes:
      - ./assets:/var/www/discourse/public/assets/
      - ./log:/var/www/discourse/log/
