services:
  - type: web
    name: discourse
    env: docker
    region: ohio
    plan: starter
    healthCheckPath: /srv/status
    dockerfilePath: discourse.Dockerfile
    envVars:
      - key: DISCOURSE_HOSTNAME
        sync: false
      - key: DISCOURSE_DB_HOST
        fromDatabase:
          name: discourse
          property: host
      - key: DISCOURSE_DB_PORT
        fromDatabase:
          name: discourse
          property: port
      - key: DISCOURSE_DB_NAME
        fromDatabase:
          name: discourse
          property: database
      - key: DISCOURSE_DB_USERNAME
        fromDatabase:
          name: discourse
          property: user
      - key: DISCOURSE_DB_PASSWORD
        fromDatabase:
          name: discourse
          property: password
      - key: DISCOURSE_REDIS_HOST
        fromService:
          type: redis
          name: discourse-redis
          property: host
      - key: DISCOURSE_REDIS_PORT
        fromService:
          type: redis
          name: discourse-redis
          property: port
      # - key: DISCOURSE_REDIS_PASSWORD
      #   fromService:
      #     type: redis
      #     name: discourse-red
      #     property: password
      - key: DISCOURSE_DEVELOPER_EMAILS
        sync: false
      - key: DISCOURSE_SMTP_DOMAIN
        sync: false
      - key: DISCOURSE_SMTP_PASSWORD
        sync: false
      - key: DISCOURSE_S3_SECRET_ACCESS_KEY
        generateValue: true
      - key: DISCOURSE_NOTIFICATION_EMAIL
        sync: false
  - type: redis
    name: discourse-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
    region: ohio
  - type: web
    name: discourse-minio
    env: docker
    region: ohio
    plan: starter
    dockerfilePath: minio.Dockerfile
    healthCheckPath: /minio/health/live
    disk:
      name: minio-data
      mountPath: /data
    envVars:
      - key: MINIO_DOMAIN
        fromService:
          type: web
          name: discourse
          envVarKey: DISCOURSE_HOSTNAME
      - key: MINIO_ROOT_PASSWORD
        fromService:
          type: web
          name: discourse
          envVarKey: DISCOURSE_S3_SECRET_ACCESS_KEY
databases:
  - name: discourse
    region: ohio
    ipAllowList: []
