services:
  - type: web
    name: discourse
    env: docker
    region: ohio
    plan: free
    healthCheckPath: /srv/status
    dockerCommand: >
      env
      DISCOURSE_S3_ENDPOINT=http://$DISCOURSE_HOSTNAME
      DISCOURSE_S3_CDN_URL=//assets.$DISCOURSE_HOSTNAME
      /tmp/start.sh
    envVars:
      - key: DISCOURSE_HOSTNAME
        sync: false
      - key: DISCOURSE_DB_HOST
        fromDatabase:
          name: discourse
          property: host
      - key: DISCOURSE_DB_PORT
        fromDatabase:
          name: discourse
          property: port
      - key: DISCOURSE_DB_NAME
        fromDatabase:
          name: discourse
          property: database
      - key: DISCOURSE_DB_USERNAME
        fromDatabase:
          name: discourse
          property: user
      - key: DISCOURSE_DB_PASSWORD
        fromDatabase:
          name: discourse
          property: password
      - key: DISCOURSE_REDIS_HOST
        fromService:
          type: redis
          name: discourse-redis
          property: host
      - key: DISCOURSE_REDIS_PORT
        fromService:
          type: redis
          name: discourse-redis
          property: port
      # - key: DISCOURSE_REDIS_PASSWORD
      #   fromService:
      #     type: redis
      #     name: discourse-red
      #     property: password
      - key: DISCOURSE_DEVELOPER_EMAILS
        sync: false
      - key: DISCOURSE_SMTP_ADDRESS
        value: smtp.sendgrid.net
      - key: DISCOURSE_SMTP_DOMAIN
        sync: false
      - key: DISCOURSE_SMTP_USER_NAME
        value: apikey
      - key: DISCOURSE_SMTP_PASSWORD
        sync: false
      - key: DISCOURSE_SMTP_PORT
        value: 587
      - key: DISCOURSE_SMTP_ENABLE_START_TLS
        value: true
      - key: DISCOURSE_USE_s3
        value: true
      - key: DISCOURSE_S3_REGION
        value: whatever
      - key: DISCOURSE_S3_ACCESS_KEY_ID
        value: minioadmin
      - key: DISCOURSE_S3_SECRET_ACCESS_KEY
        fromService:
          type: web
          name: discourse-minio
          envVarKey: MINIO_ROOT_PASSWORD
      - key: DISCOURSE_S3_BUCKET
        value: assets
      - key: DISCOURSE_S3_INSTALL_CORS_RULE
        value: false
  - type: redis
    name: discourse-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction
  - type: web
    name: discourse-minio
    env: docker
    region: ohio
    plan: free
    dockerfilePath: minio.Dockerfile
    healthCheckPath: /minio/health/live
    disk:
      name: minio-data
      mountPath: /data
    envVars:
      - key: MINIO_DOMAIN
        fromService:
          type: web
          name: discourse
          envVarKey: DISCOURSE_HOSTNAME
      - key: MINIO_ROOT_PASSWORD
        generateValue: true
databases:
  - name: discourse
